---


- name: Include Master Variables List
  include_vars: "{{ item }}"
  with_items:
     - roles/group_vars/all/vars.yml
     - roles/group_vars/java/vars.yml

- name: disable UAC pop up for Administrators
  win_regedit:
    key: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    value: ConsentPromptBehaviorAdmin
    data: 00000000
    datatype: dword

- name: Set WinLogin for DefaultUserName
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultUserName
    data: "{{ user }}"
 
- name: Set WinLogin for DefaultPassword
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultPassword
    data: "{{ user }}"

- name: Set WinLogin for AutoAdminLogon
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: 1

- name: Disable Windows Updates Services on Windows Host
  win_service:
    name: AmazonSSMAgent
    start_mode: disabled
    state: stopped
  when: mode==up

- name: Remove Service AmazonSSMAgent
  win_service:
    name: AmazonSSMAgent
    state: absent
  when: mode==up

 
- name: Create Jenkins Folders
  win_file:
    path: '{{ target_drive }}\{{ item }}'
    state: directory
  with_items:
     - seleniumgridnode
     - ssm



- name: Copy ssm agent batch file to Win Startup
  win_copy:
    src: dest-files/run-ssm-agent.bat
    dest: '{{ target_drive }}\seleniumgridnode\run-ssm-agent.bat'


- name: Copy ssm agent link file to Win Startup
  win_copy:
    src: dest-files/run-ssm-agent.bat.lnk
    dest: '{{ target_drive }}\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\run-ssm-agent.bat.lnk'

- name: Copy ssm agent link file to Win Startup
  win_copy:
    src: dest-files/connect-to-hub.bat
    dest: '{{ target_drive }}\ssm\connect-to-hub.bat'



#- name: Create batchfile shortcut on the startup
#  win_shortcut:
#    src: '{{ target_drive }}\seleniumgridnode\run-ssm-agent.bat'
#    dest: '{{ target_drive }}\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\run-ssm-agent.bat.lnk'
#    directory: '{{ target_drive }}\seleniumgridnode'

