# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


config = YAML.load_file(File.join(File.dirname(__FILE__), 'vars.yml'))
curconfigname = config['configs']['current']
config_vm = config['configs'][curconfigname]['vm']
config_winrm = config['configs'][curconfigname]['winrm']
config_aws = config['configs'][curconfigname]['aws']
config_ansible = config['configs'][curconfigname]['ansible']
config_ssh = config['configs'][curconfigname]['ssh']


Vagrant.configure(2) do |config|
        config.vm.synced_folder '.', '/vagrant', disabled: true
	
	config.vm.box = "dummy" 
  	#config.ssh.insert_key = false

        config.vm.communicator = config_vm["communicator"]
	config.vm.guest = :windows
 	config.winrm.username = config_winrm["username"]
  	config.winrm.password = config_winrm["password"]
  	config.winrm.operation_timeout_sec=60
  	config.winrm.read_timeout_sec=70
  	config.winrm.retry_limit=600
  	config.winrm.retry_delay=600
  	config.vm.boot_timeout=600
  	config.vm.graceful_halt_timeout=600

 	config.vm.provider :aws do |aws, override|

        aws.access_key_id = config_aws["access_key_id"]
        aws.secret_access_key = config_aws["secret_access_key"]

        aws.region_config config_aws["region_config"], :ami => config_aws["ami"]
  	aws.keypair_name = config_aws["keypair_name"]
  	aws.instance_type = config_aws["instance_type"] 
  	aws.subnet_id = config_aws["subnet_id"]
 	aws.associate_public_ip = config_aws["associate_public_ip"]
  	aws.security_groups =  config_aws["security_groups"]   
  	aws.private_ip_address = config_aws["private_ip_address"]
	aws.iam_instance_profile_name= config_aws["iam_instance_profile_name"]
	aws.tags = {
          		"Name" => config_aws["hostname"],
			"InstanceType" => "SELENIUM-WORKER-WIN10",
        		}
 	aws.block_device_mapping = [
            {
                'DeviceName' => config_aws["devicename"],
                'VirtualName' => config_aws["virtualname"],
                'Ebs.VolumeSize' => config_aws["ebsvolumesize"],
                'Ebs.DeleteOnTermination' => config_aws["deleteontermination"]
            }
        ]
        #override.ssh.username = config_ssh["username"]
	#override.ssh.private_key_path = config_ssh["private_key_path"] + config_ssh["private_key_pemfilename"]

 	 end
  	config.vm.provision "ansible" do |ansible|
   		ansible.playbook = config_ansible["playbook_filename"]
  	end
 end







