---

- name: Include Master Variables List
  include_vars: "{{ item }}"
  with_items:
     - roles/group_vars/all/vars.yml
     - roles/group_vars/swarm/vars.yml

- name: Create Jenkins Folders
  become: yes
  file:
    path: /home/{{ item }}
    state: directory
  with_items:
     - jenkins
     - jenkins/agent

- name: Download Git from repository
  become: yes
  get_url:
    url: "{{ artifactory_url }}/{{ artifact_swarm_path }}/{{ item }}"
    url_username: "{{ artifactory_username }}"
    url_password: "{{ artifactory_password }}"
    dest: /home/jenkins/agent/{{ item }}
  with_items:
    - '{{ swarm_artifact }}'
    - '{{ swarm_batch }}'

- name: Download Batch file from repository
  become: yes
  get_url:
    url: "{{ artifactory_url }}/{{ artifact_swarm_path }}/{{ item }}"
    url_username: "{{ artifactory_username }}"
    url_password: "{{ artifactory_password }}"
    dest: /root/{{item }}
  with_items:
    - '{{ swarm_batch }}'

- name: Add line to rc.local
  become: yes
  lineinfile:
    path: /etc/rc.d/rc.local
    line: '/root/{{ swarm_batch }}'

- name: Give files priv
  become: yes
  file: 
    path: "{{ item }}"
    mode: 0777
  with_items:
    - /home/jenkins/agent/{{ swarm_artifact }}
    - /home/jenkins/agent/{{ swarm_batch }}
    - /root/{{ swarm_batch }}
    - /etc/rc.d/rc.local

- name: Restart server
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true




   


  